# Generated by Django 5.1 on 2024-10-21 10:01

import form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128, validators=[form.models.validate_password])),
                ('date_of_birth', models.DateField(validators=[form.models.validate_age])),
            ],
        ),
    ]
